### ISSUE TITLE
Some pages are crashing on the live site

### ISSUE THREAD

**Issue by adrianthedev** [marcoroth/hotwire.io#40]
Not sure if you are aware of this.

https://hotwire.io/documentation/turbo/handbook/02_drive

![CleanShot 2023-10-17 at 16 50 51@2x](https://github.com/marcoroth/hotwire.io/assets/1334409/efd13e83-c9bd-4529-af07-b803f05fd734)

**Comment by marcoroth** [comment]
Yeah, sadly the state of git submodules on Heroku is not great. It's currently failing because the automatic deployment via GitHub doesn't initialize git submodles. 

I'm not sure what the best way would be to incorporate the upstream documentation without have to actually copy it into the repo.

I guess the other option is that we fetch the documentation at runtime via HTTP requests and cache it in the app.

**Comment by adrianthedev** [comment]
How about fetching them in the build step? Would that be an alternative? It would definitely be more performant.

**Comment by marcoroth** [comment]
Right, that's a good idea. We'd just need to make sure that you can also run and see the content locally while developing, so it should probably be something like a rake-task that spits out the generated files.

**Comment by adrianthedev** [comment]
Yes. a Script that you could run from time to time that will output the files in the directory, and you manually commit to the repo.
Then they will be available as regular HTML files
